[package]
name = "mp4iter"
version = "0.5.0"
edition = "2021"
license = "MIT"
authors = ["Jens Larsson <jens.dev@fastmail.com"]
keywords = ["MP4", "video", "parse"]

[dependencies]
binrw = "0.14"
rayon = "1.10.0"
time = {version = "0.3.37", features = ["formatting"]}
