[package]
name = "mp4iter"
version = "0.4.0"
edition = "2021"
authors = ["Jens Larsson <jens.dev@fastmail.com"]

[dependencies]
binrw = "0.14"
rayon = "1.10.0"
time = {version = "0.3.36", features = ["formatting"]}
